{
 "title": "State of CI",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "workflow",
    "label": "Workflow",
    "query": {
     "query": "label_values(github_workflow_status{repository=\"$repository\", branch=\"$branch\", trigger=\"$trigger\"},workflow)"
    }
   },
   {
    "name": "repository",
    "label": "Repository",
    "query": {
     "query": "label_values(github_workflow_status,repository)"
    }
   },
   {
    "name": "branch",
    "label": "Branch",
    "query": {
     "query": "label_values(github_workflow_status{repository=\"$repository\"},branch)"
    }
   },
   {
    "name": "trigger",
    "label": "Trigger",
    "query": {
     "query": "label_values(github_workflow_status{repository=\"$repository\", branch=\"$branch\"},trigger)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall state",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "10 - (count(\n  github_workflow_status{repository=\"$repository\", branch=\"$branch\", trigger=\"$trigger\"} <= 2\n)\nor\nvector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows succeeded",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(github_workflow_status{repository=\"$repository\", branch=\"$branch\", trigger=\"$trigger\"} == 10)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows in progress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(github_workflow_status{repository=\"$repository\", branch=\"$branch\", trigger=\"$trigger\"} == 9)\nor\nvector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows failed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(github_workflow_status{repository=\"$repository\", branch=\"$branch\", trigger=\"$trigger\"} <= 2)\nor\nvector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$workflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "workflow" },
  {
   "title": "$workflow",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_workflow_status{workflow=~\"$workflow\", branch=\"$branch\", trigger=\"$trigger\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$workflow status over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "github_workflow_status{workflow=~\"$workflow\", branch=\"$branch\", trigger=\"$trigger\"}",
     "legendFormat": "{{workflow}}"
    }
   ]
  }
 ]
}