name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: "3.x"

      - name: Generate version
        id: version
        run: |
          MAJOR=1  # You can manually update this when needed
          MINOR=0  # You can manually update this when needed
          PATCH=${{ github.run_number }}
          echo "version=$MAJOR.$MINOR.$PATCH" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
