name: Publish Helm Chart to GHCR

on:
  push:
    tags:
      - "*-helm"

env:
  CHART_DIR: charts/github-actions-exporter-charts

jobs:
  publish:
    name: Push Helm Chart as OCI
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Lint Helm chart
        run: |
          helm lint $CHART_DIR

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u replaid-inc --password-stdin

      - name: Push chart to GHCR
        run: |
          # extract chart version from Chart.yaml
          VERSION=$(yq '.version' $CHART_DIR/Chart.yaml)
          CHART_NAME=$(yq '.name' $CHART_DIR/Chart.yaml)

          # export chart as .tgz
          helm package $CHART_DIR --destination .

          # push to OCI
          helm push ${CHART_NAME}-${VERSION}.tgz oci://ghcr.io/replaid-inc/github-actions-exporter-charts
