{{- if .Values.githubWebhookSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.githubWebhookSecret.name | default "github-webhook-secret" }}
  labels:
    {{- include "github-actions-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.githubWebhookSecret.value | b64enc }}
{{- end }}
